apiVersion: v1
kind: Service
metadata:
    name: app-service
    namespace: app
spec:
    type: NodePort
    selector:
        app: simple-app
    ports:
        - port: 8080
          name: simple-app
          targetPort: 8080
          nodePort: 30001