pipeline {
    agent any

    tools {
        maven 'maven'
    }

    stages {
        stage('Pull') {
            steps {
                git url: "${githubURL}", branch: "${gitBranch}"
            }
        }
        stage('Checkstyle') {
            steps {
                dir("simple-app") {
                    sh "mvn validate"
                }
            }
        }
        stage('Test') {
            steps {
                dir("simple-app") {
                    sh "mvn test -Dcheckstyle.skip=true"
                }
            }
        }
        stage('Build') {
            steps {
                dir("simple-app") {
                    sh "mvn package -DskipTests=true -Dcheckstyle.skip=true"
                }
            }
        }
        stage('Upload Docker Image') {
            steps {
                script {
                    dir("simple-app") {
                        docker.withTool('docker') {
                            repoId = "aarondownward/simple-app"
                            image = docker.build(repoId)
                            docker.withRegistry("https://registry.hub.docker.com", "dockerhub-cred") {
                                image.push()
                            }
                        }
                    }
                }
            }
        }
        stage('Rollout deployment')
        {
            steps {
                sh 'kubectl rollout restart deployment/simple-app'
            }
        }
    }
}